# Yazi Configuration
# Configured for use with the Tokyo Night Night theme

[mgr]
ratio          = [ 1, 4, 3 ]
sort_by        = "alphabetical"
sort_sensitive = false
sort_reverse   = false
sort_dir_first = true
linemode       = "none"
show_hidden    = true
show_symlink   = true

[preview]
tab_size   = 2
max_width  = 1200
max_height = 1800

[opener]
# Define custom file openers here if needed

[open]
# Custom open rules here if needed

[tasks]
micro_workers    = 10
macro_workers    = 25
bizarre_retry    = 5
image_alloc      = 536870912  # 512MB
image_bound      = [ 0, 0 ]
suppress_preload = false

[plugin]

[log]
enabled = false
